### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alefvanoon** [LukeSmithxyz/lugo#9]
Hi,
Does this repo have a license?
I want to use this theme.

**Comment by Gip-Gip** [comment]
I second this, I did copy/paste some of the code from this repository and it would be nice if this was under the MIT license or BSD or something alike

**Comment by LukeSmithxyz** [comment]
Is this a joke? Are you going to email someone for a license to use their CSS?

Here's a license: Only people who don't care about licenses can use this.

**Comment by Gip-Gip** [comment]
> Is this a joke? Are you going to email someone for a license to use their CSS?
> 
> Here's a license: Only people who don't care about licenses can use this.

As dumb as it is you can still sue anyone that uses your code even though it is posted online, and it would be unwise for anyone to derive anything from unlicensed code because of this fact. While I'm sure you wouldn't do anything like that (since you did post your code online) it is still a good idea to have your OSS under at least some legal license stating people can freely use and derive your works. Simply to ensure the protection of other's rights.

My two cents, but it is your project so do as you please
